### ISSUE TITLE
There's no public API for setting Injector._ejectOnDispose

### ISSUE THREAD

**Issue by psytrx** [aevitas/bluerain#10]
As the Injector constructor is internal, theres just `ExternalProcessMemory.ctor` to instantiate an Injector. However, there's no way to set `_ejectOnDispose` if you want the injected modules to get free'd.

Ideas:

- Expose `_ejectOnDispose` as a public get/set property
  - as long as there aren't too many options to pass, this might be a simple and clean solution
- Add `InjectorInitializationParameters` to the `ExternalProcessMemory.ctor`
  - This can also bundle `createInjector`, which seems like a clean approach
- Pass it as an optional argument to `ExternalProcessMemory.ctor`
  - this may clutter the API as well as being a breaking change

**Comment by aevitas** [comment]
Implemented via `InjectorCreationOptions`, which is a breaking change but allows for more granularity in injector behaviour configuration.

Users of the memory classes can specify whether they want their library to be freed when the instance is disposed through this option type when constructing either an `ExternalProcessMemory` or `LocalProcessMemory` instance.
