### ISSUE TITLE
about marshalling

### ISSUE THREAD

**Issue by fabio24021990** [aevitas/bluerain#5]
hi, i tested a method inspirated by yours like 👍 

`Marshal.SizeOf(typeof(T));` to get the buffer size in generic Read<T> method... i got it work with an integer

is that a correct way to doit?

**Comment by aevitas** [comment]
Yes, the return value of `Marshal.SizeOf` is an integer. If you're using BlueRain you shouldn't need to determine the size though - the library handles all that for you.

**Comment by lolp1** [comment]
@fabio24021990 @aevitas I think .NET is making Marshal.SizeOf(Type) obsolete in favor of the new Marshal.SizeOf<T>()
